version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - activemq
    restart: on-failure
    environment:
      DATABASE_URL: "jdbc:mysql://mysqldb:3306/aptDb?useSSL=false&allowPublicKeyRetrieval=true"
      DATABASE_USER: "myuser"
      DATABASE_PASSWORD: "mypassword"
      BROKER_URL: "tcp://activemq:61616"
      BROKER_USER: "admin"
      BROKER_PASSWORD: "admin"
      EMAIL_FROM: "mushtaq.hussain@sunknowledge.com"
      EMAIL_PASSWORD: "m@h$11%01#46"
      EMAIL_HOST: "smtp.office365.com"
      EMAIL_PORT: "587"
      EMAIL_PROTOCOL: "smtp"
      EMAIL_AUTH: "true"
      EMAIL_STARTTLS: "true"
      EMAIL_DEBUG: "true"
      # Add other environment variables as needed
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "aptDb"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_ROOT_PASSWORD: "myrootpassword"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  activemq:
    image: rmohr/activemq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: "admin"
      ACTIVEMQ_ADMIN_PASSWORD: "admin"
volumes:
  mysql_data:
