version: '3'
services:
  app:
    image: ${DOCKER_REGISTRY-}apt-app:latest
    ports:
     - "${APP_PORT:-8080}:8080"
    depends_on:
      - mysqldb
      - activemq
    restart: on-failure
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      BROKER_URL: ${BROKER_URL}
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_PROTOCOL: ${EMAIL_PROTOCOL}
      EMAIL_AUTH: ${EMAIL_AUTH}
      EMAIL_STARTTLS: ${EMAIL_STARTTLS}
  mysqldb:
    image: ${DOCKER_REGISTRY-}mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
    - ${MYSQL_PORT}
    volumes:
    - ${MYSQL_VOLUME}:/var/lib/mysql
  activemq:
    image: ${DOCKER_REGISTRY-}rmohr/activemq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: ${ACTIVEMQ_ADMIN_LOGIN}
      ACTIVEMQ_ADMIN_PASSWORD: ${ACTIVEMQ_ADMIN_PASSWORD}
volumes:
  mysql_data: