#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/aptDb?useSSL=false&allowPublicKeyRetrieval=true
#    username: myuser
#    password: mypassword
#    driverClassName: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect # Updated dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#  activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: chrisgodswill09@gmail.com
#    password: kelvinkrys
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#  sql:
#    init:
#      mode: always
#  profiles:
#    active: prod
#
#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework:
#        security: DEBUG
#debug: true
