name: Build and deploy Acaree to AWS
on:
  push:
    branches:
      - appointment-schedule
  pull_request:
    branches:
      - appointment-schedule
jobs:
  build-deploy:
    name: Build and deploy Acaree to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
        distribution: 'corretto'
        java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build application
        run: |
          mvn clean
          mvn -B package --file pom.xml
        




