spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  spring:
    activemq:
      broker-url: tcp://localhost:61616
      user: admin
      password: admin
      packages:
        trust-all: true


h2:
  console:
    enabled: true
    path: /h2-console

logging:
  level:
    root: DEBUG




# Additional configuration
#server:
#  port: 8080

# Security, logging, or other configurations can go here
